using System;
using System.Collections.Generic;
using System.Linq;
using System.Collections;
using UnityEngine;
using HATAGONG.GameFlow;

namespace HATAGONG.Phase1
{
    public sealed class Phase1BoardController : MonoBehaviour
    {
        [SerializeField] private RectTransform fieldRoot,tileContainer,effectRoot,scorePopupRoot;
        [SerializeField] private Phase1TileView tilePrefab; [SerializeField] private Phase1GameConfig config;
        [SerializeField] private Phase1InputController inputController; [SerializeField] private Phase1ScoreController scoreController; [SerializeField] private Phase1FeedbackController feedbackController; [SerializeField] private Phase1HUDPresenter hudPresenter;
        [SerializeField] private GameSessionController sessionController;
        [SerializeField] private bool generateOnStart=true; [SerializeField] private Phase1Difficulty difficulty=Phase1Difficulty.Normal;
        [SerializeField] private bool useFixedSeed; [SerializeField] private int fixedSeed=12345; [SerializeField] private bool ignoreSessionHistoryForDebug;
        [SerializeField] private bool runSmokeTestOnStart;
        [SerializeField] private int currentSeed; [SerializeField] private string currentBagId,currentLayoutHash,currentVariantHash;
        private readonly Phase1ShuffleBag shuffle=new();private readonly Dictionary<Phase1Difficulty,Queue<string>> hashes=new();private readonly List<Phase1TileView> views=new();private Phase1BoardState state;private int remaining,totalHits,superSelectionSeed;private float started,lastDirectHitAt=-999f,lastFatigueLogAt=-999f;private bool cleared,smokeStarted,prepared,hardEffect,superEffect,fatigueEffect;
        public event Action Phase1ClearConditionReached;public event Action<Phase1BoardState> Phase1Cleared;public Phase1HitResult LastHitResult{get;private set;}public bool IsPrepared=>prepared&&state!=null;
        public int CurrentSeed=>currentSeed;public string CurrentLayoutHash=>currentLayoutHash;public string CurrentVariantHash=>currentVariantHash;
        public float EffectiveDirectHitInterval=>RequestEffectRuntime.GetPhase1HitInterval(fatigueEffect);public int SuperTileCount=>views.Count(view=>view&&view.IsSuperTile);
        public bool CanPlayTouchEffect=>IsPrepared&&!cleared&&sessionController&&sessionController.CanAcceptGameplayInput&&inputController&&inputController.InputEnabled;
        private void Start(){if(config){config.EnsureDefaults();generateOnStart=config.GenerateOnStart&&generateOnStart;}if(generateOnStart&&!IsPrepared)Prepare(difficulty);if(runSmokeTestOnStart&&state!=null)RunSmokeTestImmediate();}
        private void Update(){if(runSmokeTestOnStart&&state!=null&&!smokeStarted){smokeStarted=true;StartCoroutine(RunSmokeTest());}}
        [ContextMenu("Generate Board")] public void GenerateBoard(){if(!IsPrepared)Prepare(difficulty);}
        [ContextMenu("Regenerate Board")] public void RegenerateBoard(){ClearPreparedBoard();Prepare(difficulty);}
        public void ConfigureRequestEffects(GameRunContext context){bool nextHard=context.HasEffect(RequestEffectRuntime.Hard),nextSuper=context.HasEffect(RequestEffectRuntime.Super),nextFatigue=context.HasEffect(RequestEffectRuntime.Fatigue);int nextSuperSeed=nextSuper?context.PermanentSeed:0;bool generationChanged=hardEffect!=nextHard||superEffect!=nextSuper||superSelectionSeed!=nextSuperSeed;hardEffect=nextHard;superEffect=nextSuper;fatigueEffect=nextFatigue;superSelectionSeed=nextSuperSeed;lastDirectHitAt=-999f;if(generationChanged&&IsPrepared)ClearPreparedBoard();}
        public bool Prepare(Phase1Difficulty targetDifficulty)=>PrepareInternal(targetDifficulty,null);
        public bool Prepare(Phase1Difficulty targetDifficulty,int requestedSeed)=>requestedSeed>0&&PrepareInternal(targetDifficulty,requestedSeed);
        private bool PrepareInternal(Phase1Difficulty targetDifficulty,int? requestedSeed)
        {
            inputController?.SetInputEnabled(false);
            if(IsPrepared)return state.Difficulty==targetDifficulty&&(!requestedSeed.HasValue||state.Seed==requestedSeed.Value);
            difficulty=targetDifficulty;
            if(Generate(requestedSeed)){prepared=true;return true;}
            ClearPreparedBoard();
            return false;
        }
        private bool Generate(int? requestedSeed=null)
        {
            if(!config||!fieldRoot||!tileContainer||!tilePrefab||!inputController||!scoreController||!feedbackController){Debug.LogError("[Phase1] Required Inspector references are missing.");return false;}
            config.EnsureDefaults();if(!config.ValidateAllBags())return false;var seed=requestedSeed??(useFixedSeed?fixedSeed:Environment.TickCount);var random=new System.Random(seed);var generator=new Phase1BoardGenerator(config);Phase1BoardState next=null;
            if(useFixedSeed&&ignoreSessionHistoryForDebug&&state!=null){var replayBag=config.Bags.FirstOrDefault(x=>x.Id==state.BagId);if(replayBag!=null&&generator.TryGenerate(difficulty,replayBag,fixedSeed,true,out var replay)){Commit(replay);return true;}Debug.LogError($"[Phase1] Fixed-seed debug replay failed for bag={state.BagId}, seed={fixedSeed}.");return false;}
            var bags=shuffle.OrderedCandidates(difficulty,config.Bags,random).Select(id=>config.Bags.First(x=>x.Id==id)).ToList();
            for(int b=0;b<bags.Count&&next==null;b++){int attempts=requestedSeed.HasValue?1:(b==0?config.CurrentBagAttempts:config.AlternativeBagAttempts);for(int a=0;a<attempts;a++){int attemptSeed=requestedSeed??(seed+(b*1000)+a);if(generator.TryGenerate(difficulty,bags[b],attemptSeed,true,out var candidate)&&(requestedSeed.HasValue||AcceptHash(candidate.LayoutHash))){next=candidate;break;}}}
            if(next==null&&!requestedSeed.HasValue)foreach(var bag in bags){for(int a=0;a<config.AlternativeBagAttempts;a++){int attemptSeed=seed+100000+a;if(generator.TryGenerate(difficulty,bag,attemptSeed,false,out var candidate)&&AcceptHash(candidate.LayoutHash)){next=candidate;break;}}if(next!=null)break;}
            if(next==null){Debug.LogError($"[Phase1] Generation failed. Bags tried: {string.Join(",",bags.Select(x=>x.Id))}");return false;}
            Commit(next);shuffle.MarkSuccessful(difficulty,next.BagId);RememberHash(next.LayoutHash);return true;
        }
        private bool AcceptHash(string hash)=>ignoreSessionHistoryForDebug||!hashes.TryGetValue(difficulty,out var q)||!q.Contains(hash);
        private void RememberHash(string hash){if(ignoreSessionHistoryForDebug)return;if(!hashes.TryGetValue(difficulty,out var q))hashes[difficulty]=q=new Queue<string>();q.Enqueue(hash);while(q.Count>config.HashCapacity(difficulty))q.Dequeue();}
        private void Commit(Phase1BoardState next){ApplyRequestEffects(next);foreach(var v in views)if(v)Destroy(v.gameObject);views.Clear();state=next;currentSeed=next.Seed;currentBagId=next.BagId;currentLayoutHash=next.LayoutHash;currentVariantHash=next.VariantHash;remaining=next.Tiles.Count;totalHits=0;cleared=false;lastDirectHitAt=-999f;started=Time.unscaledTime;hudPresenter?.Present(difficulty);float cell=fieldRoot.rect.width/config.BoardSize;
            foreach(var p in next.Tiles){var v=Instantiate(tilePrefab,tileContainer);v.name=$"Phase1_Tile_{p.TileId:00}_{p.Shape}";var rt=(RectTransform)v.transform;rt.anchorMin=rt.anchorMax=rt.pivot=new Vector2(0,1);rt.anchoredPosition=new Vector2(p.GridX*cell,-p.GridY*cell);rt.sizeDelta=new Vector2(p.GridWidth*cell,p.GridHeight*cell);rt.localScale=Vector3.one;rt.localRotation=Quaternion.identity;v.Initialize(p,inputController,config);views.Add(v);}var superTile=next.Tiles.FirstOrDefault(x=>x.IsSuperTile);int unbalancedTotal=next.Tiles.Sum(x=>x.BaseHp+x.GradeHpModifier),balancedTotal=next.Tiles.Sum(x=>x.BaseHp+x.GradeHpModifier+x.BalanceHpModifier),largestArea=next.Tiles.Count>0?next.Tiles.Max(x=>x.GridWidth*x.GridHeight):0,largestCandidateCount=next.Tiles.Count(x=>x.GridWidth*x.GridHeight==largestArea);Debug.Log($"[RequestEffect][Phase1] hard={hardEffect}, totalTiles={next.Tiles.Count}, unbalancedHpTotal={unbalancedTotal}, balancedHpTotal={balancedTotal}, hardAppliedTiles={(hardEffect?next.Tiles.Count:0)}, hardHpAdded={(hardEffect?next.Tiles.Count*RequestEffectRuntime.HardHpBonus:0)}, super={superEffect}, superCandidateCount={(superEffect?largestCandidateCount:0)}, superTileId={(superTile!=null?superTile.TileId:-1)}, superArea={(superTile!=null?superTile.GridWidth*superTile.GridHeight:0)}, superBaseHp={(superTile!=null?superTile.BaseHp+superTile.GradeHpModifier+superTile.BalanceHpModifier:0)}, superHpBonus={(superEffect?RequestEffectRuntime.SuperTileHpBonus:0)}, superFinalHp={(superTile!=null?superTile.MaxHp:0)}, finalHpTotal={next.Tiles.Sum(x=>x.MaxHp)}, fatigue={fatigueEffect}, directHitInterval={EffectiveDirectHitInterval:F2}",this);Debug.Log($"[Phase1] Generated difficulty={difficulty}, bag={currentBagId}, seed={currentSeed}, cell={cell}, layoutHash={currentLayoutHash}, variantHash={currentVariantHash}, tiles={remaining}, baseHp={next.Tiles.Sum(x=>x.BaseHp)}, gradeModifier={next.Tiles.Sum(x=>x.GradeHpModifier)}, balanceModifier={next.Tiles.Sum(x=>x.BalanceHpModifier)}, requestModifier={next.Tiles.Sum(x=>x.RequestHpModifier)}, finalHp={next.Tiles.Sum(x=>x.MaxHp)}");}
        public bool TryHit(Phase1TileView tile)=>TryHitDetailed(tile)==Phase1HitResult.Succeeded;
        public Phase1HitResult TryHitDetailed(Phase1TileView tile){if(!sessionController||!sessionController.CanAcceptGameplayInput||!inputController||!inputController.InputEnabled)return LastHitResult=Phase1HitResult.StateBlocked;if(!tile)return LastHitResult=Phase1HitResult.InvalidTarget;if(tile.IsDestroyed)return LastHitResult=Phase1HitResult.AlreadyDestroyed;float actualInterval=Time.unscaledTime-lastDirectHitAt;if(fatigueEffect&&actualInterval<RequestEffectRuntime.FatigueHitIntervalSeconds){if(Time.unscaledTime-lastFatigueLogAt>=0.5f){lastFatigueLogAt=Time.unscaledTime;Debug.Log($"[RequestEffect][FatigueBlocked] tileId={tile.TileId}, actualInterval={actualInterval:F3}, requiredInterval={RequestEffectRuntime.FatigueHitIntervalSeconds:F2}, blocked=true",this);}return LastHitResult=Phase1HitResult.DamageRejected;}int damage=IngameItemSystemController.Instance?IngameItemSystemController.Instance.Phase1DirectDamage:1;if(cleared||!ApplyDamageThroughExistingFlow(tile,damage,true))return LastHitResult=Phase1HitResult.DamageRejected;lastDirectHitAt=Time.unscaledTime;GameplayInputActivity.NotifyValidGameplayInput(GamePhaseId.Phase1);IngameItemSystemController.Instance?.NotifyPhase1DirectHit(tile,views,ApplyItemDamage);return LastHitResult=Phase1HitResult.Succeeded;}
        private void ApplyRequestEffects(Phase1BoardState next){if(next==null)return;foreach(var tile in next.Tiles){int unbalancedHp=tile.BaseHp+tile.GradeHpModifier;int balancedHp=RequestEffectRuntime.BalancePhase1Hp(unbalancedHp);tile.BalanceHpModifier=balancedHp-unbalancedHp;tile.RequestHpModifier=hardEffect?RequestEffectRuntime.HardHpBonus:0;tile.IsSuperTile=false;}if(superEffect&&next.Tiles.Count>0){int selectedId=RequestEffectRuntime.SelectLargestAreaSuperTileId(superSelectionSeed,next.Tiles.Select(candidate=>candidate.TileId).ToArray(),next.Tiles.Select(candidate=>candidate.GridWidth*candidate.GridHeight).ToArray());var tile=next.Tiles.First(candidate=>candidate.TileId==selectedId);tile.IsSuperTile=true;tile.RequestHpModifier+=RequestEffectRuntime.SuperTileHpBonus;}foreach(var tile in next.Tiles){int balancedHp=tile.BaseHp+tile.GradeHpModifier+tile.BalanceHpModifier;tile.MaxHp=balancedHp+tile.RequestHpModifier;tile.MinimumHpValid=tile.MaxHp>=config.MinimumFinalTileHp;}next.VariantHash=Phase1VariantHash.Compute(next);}
        private bool ApplyDamageThroughExistingFlow(Phase1TileView tile,int damage,bool directImpact){if(!tile||tile.IsDestroyed||!tile.ApplyDamage(damage,out var changed,out var destroyed))return false;totalHits++;scoreController.Add(config.HitScore,ScoreReason.Hit);feedbackController.Play(tile.Role,tile.Grade,changed,destroyed,directImpact);if(destroyed){tile.DestroyVisual();remaining--;scoreController.Add(config.DestroyScore,ScoreReason.Destroy);if(remaining==0)Clear();}return true;}
        private bool ApplyItemDamage(Phase1TileView tile){if(cleared||!tile)return false;Vector3 center=tile.WorldCenter;if(!ApplyDamageThroughExistingFlow(tile,1,false))return false;inputController?.PlayItemHitFeedback(center);return true;}
        private void Clear(){if(cleared)return;cleared=true;Phase1ClearConditionReached?.Invoke();scoreController.Add(config.ClearScore,ScoreReason.PhaseClear);Debug.Log($"[Phase1] Phase1Cleared bag={currentBagId}, hits={totalHits}, score={scoreController.Score}, elapsed={Time.unscaledTime-started:F3}, hash={currentLayoutHash}");Phase1Cleared?.Invoke(state);}
        [ContextMenu("Validate All Bags")] public void ValidateAllBags(){if(config)config.ValidateAllBags();}
        [ContextMenu("Print Current Layout")] public void PrintCurrentLayout(){if(state==null){Debug.Log("[Phase1] No board.");return;}Debug.Log($"[Phase1] difficulty={state.Difficulty}, bag={state.BagId}, seed={state.Seed}, layout={state.LayoutHash}, variant={state.VariantHash}, minHp={config.MinimumFinalTileHp}, baseHp={state.Tiles.Sum(x=>x.BaseHp)}, gradeModifier={state.Tiles.Sum(x=>x.GradeHpModifier)}, balanceModifier={state.Tiles.Sum(x=>x.BalanceHpModifier)}, requestModifier={state.Tiles.Sum(x=>x.RequestHpModifier)}, finalHp={state.Tiles.Sum(x=>x.MaxHp)}, violations={state.Tiles.Count(x=>!x.MinimumHpValid)}, grades={string.Join(",",state.Tiles.GroupBy(x=>x.Grade).Select(g=>$"{g.Key}:{g.Count()}"))}");foreach(var p in state.Tiles)Debug.Log($"[Phase1] tile={p.TileId}, area={p.GridWidth*p.GridHeight}, pos=({p.GridX},{p.GridY}), size=({p.GridWidth},{p.GridHeight}), shape={p.Shape}, grade={p.Grade}, baseHp={p.BaseHp}, gradeModifier={p.GradeHpModifier}, balanceModifier={p.BalanceHpModifier}, requestModifier={p.RequestHpModifier}, finalHp={p.MaxHp}, super={p.IsSuperTile}, valid={p.MinimumHpValid}, visual={p.VisualSetId}, sprite={p.UsedSpriteName}, fallback={p.VisualFallbackUsed}");}
        [ContextMenu("Damage First Alive Tile")] public void DamageFirstAliveTile(){var v=views.FirstOrDefault(x=>x&&!x.IsDestroyed);if(v)TryHit(v);}
        [ContextMenu("Destroy Current Board")] public void DestroyCurrentBoard(){ClearPreparedBoard();}
        private void ClearPreparedBoard(){foreach(var v in views)if(v)Destroy(v.gameObject);views.Clear();remaining=0;state=null;prepared=false;cleared=false;currentSeed=0;currentBagId=string.Empty;currentLayoutHash=string.Empty;currentVariantHash=string.Empty;inputController?.SetInputEnabled(false);}
        private IEnumerator RunSmokeTest()
        {
            smokeStarted=true;
            yield return null;int expectedHits=state.Tiles.Sum(x=>x.MaxHp);int expected=expectedHits*config.HitScore+state.Tiles.Count*config.DestroyScore+config.ClearScore;
            var first=views.FirstOrDefault(x=>x&&!x.IsDestroyed);var observed=new HashSet<Phase1DamageState>();
            if(first)while(!first.IsDestroyed){TryHit(first);observed.Add(first.DamageState);yield return new WaitForSecondsRealtime(config.TileDebounce+0.01f);}
            foreach(var tile in views)while(tile&&!tile.IsDestroyed){TryHit(tile);yield return new WaitForSecondsRealtime(config.TileDebounce+0.01f);}
            Debug.Log($"[Phase1][SmokeTest] bag={currentBagId}, seed={currentSeed}, expectedHits={expectedHits}, actualHits={totalHits}, expectedScore={expected}, actualScore={scoreController.Score}, cleared={cleared}, states={string.Join(",",observed)}, hash={currentLayoutHash}");
        }
        private void RunSmokeTestImmediate()
        {
            smokeStarted=true;int expectedHits=state.Tiles.Sum(x=>x.MaxHp);int expected=expectedHits*config.HitScore+state.Tiles.Count*config.DestroyScore+config.ClearScore;var observed=new HashSet<Phase1DamageState>();int clearEvents=0;Action<Phase1BoardState> clearHandler=_=>clearEvents++;Phase1Cleared+=clearHandler;
            var first=views.FirstOrDefault(x=>x&&!x.IsDestroyed);var second=views.FirstOrDefault(x=>x&&x!=first&&!x.IsDestroyed);bool firstPointer=false,multiPointerBlocked=false,debounceBlocked=false,differentTileAllowed=false;
            if(first){first.DebugAllowImmediateHit();firstPointer=inputController.TryBegin(101,first);int scoreAfterFirst=scoreController.Score;multiPointerBlocked=second&&!inputController.TryBegin(202,second)&&scoreController.Score==scoreAfterFirst;inputController.End(101);debounceBlocked=!inputController.TryBegin(303,first)&&scoreController.Score==scoreAfterFirst;inputController.End(303);}
            if(second){second.DebugAllowImmediateHit();differentTileAllowed=inputController.TryBegin(404,second);inputController.End(404);}
            if(first)while(!first.IsDestroyed){first.DebugAllowImmediateHit();TryHit(first);observed.Add(first.DamageState);}
            foreach(var tile in views)while(tile&&!tile.IsDestroyed){tile.DebugAllowImmediateHit();TryHit(tile);}
            int finalScore=scoreController.Score;bool destroyedInputBlocked=first&&!inputController.TryBegin(505,first)&&scoreController.Score==finalScore;inputController.End(505);Phase1Cleared-=clearHandler;
            Debug.Log($"[Phase1][SmokeTest] bag={currentBagId}, seed={currentSeed}, expectedHits={expectedHits}, actualHits={totalHits}, expectedScore={expected}, actualScore={scoreController.Score}, cleared={cleared}, clearEvents={clearEvents}, firstPointer={firstPointer}, multiPointerBlocked={multiPointerBlocked}, debounceBlocked={debounceBlocked}, differentTileAllowed={differentTileAllowed}, destroyedInputBlocked={destroyedInputBlocked}, states={string.Join(",",observed)}, hash={currentLayoutHash}");
        }
    }
}
